### ISSUE TITLE
Pure go data migrations require empty cql file

### ISSUE THREAD

**Issue by ajankovic** [scylladb/gocqlx#101]
CQL files are needed to create migrations. In situations where go migration code is needed to create data only migrations, CQL file becomes superficial.

Workaround for this is to use empty file and attach go code execution as callback. But empty CQL file is not accepted so workaround for this is to use some read only statement in the CQL file to make sure go callback is executed.

This all feel kinda hackish and should probably be given consideration in the future.

**Comment by mmatczuk** [comment]
https://flywaydb.org/documentation/migrations#java-based-migrations
