### ISSUE TITLE
Await schema agreement post migration

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/gocqlx#106]
This requires a patch to gocql. Gocql has a function `awaitSchemaAgreement` to wait for schema to be propagated to all the nodes. We should export that to Session. When done we should call it post each migration.

**Comment by dahankzter** [comment]
So the normal notification flow here isn't enough? Is it just too slow to pick up on that?

**Comment by mmatczuk** [comment]
Waiting for keyspace changed events will not work, for instance if you only add data there is not keyspace change.

**Comment by powerman** [comment]
Is there any workaround which can be used right now?

**Comment by mmatczuk** [comment]
Yes use a single host to run all the migrations. You can check that by issuing describe schema queries to different hosts.

**Comment by annismckenzie** [comment]
I'm working on this in #133. Still working out the kinks (gocql test suite is failing for some combinations on Travis, incidentally only those that have auth enabled – weird).

**Comment by mmatczuk** [comment]
Kudos for working on it.

**Comment by mmatczuk** [comment]
Fixed in #133
