### ISSUE TITLE
Is it possible to filter database columns based on destination struct?

### ISSUE THREAD

**Issue by shreesharao** [scylladb/gocqlx#107]
Is there a way to filter database columns based on destination struct? , Now If the destination column is not present then StructMap throws an error. for example, I need to select 100 columns out of 150 columns and I do not want to specify each column name when selecting.

**Comment by dahankzter** [comment]
What does your struct look like? Does it use the `db` type annotation to name the columns?

**Comment by dahankzter** [comment]
Better yet, do you have a small repeatable program I can try?

**Comment by mmatczuk** [comment]
Yes it's possible.
