### ISSUE TITLE
Cannot use same column for relational queries in select

### ISSUE THREAD

**Issue by kabaluyot** [scylladb/gocqlx#108]
Since the Select in qb utilizes map[string]interface{}, I cannot give in between queries.

Example, I have this query, `date >= '2019-07-30' and date <= '2019-08-15'`. Binding it to qb.Cond and q.Map gives `{"date": "2019-07-30", "date":"2019-08-15"}` which is invalid in for map[string]interface{}.

How would you bind this?

**Comment by kabaluyot** [comment]
I see that to get a unique list in qb.Map, I need a custom parameter name for the qb.Cmp. Thus I solve this by using "Named", EqNamed, etc., assigning it with key since it is in for loop, and everything works.

**Comment by tartale** [comment]
@kabaluyot I had this same issue, do you mind posting a code example that demonstrates your solution?  TIA!!

**Comment by kabaluyot** [comment]
Hi @tartale , say you wanted you "where" to have `date >= '2019-07-30' and date <= '2019-08-15'`, In my case:

```go
// query holds the SelectBuilder
query := qb.Select("trades")

// bindMap holds the query named parameters that will be binded to your cql query
bindMap := qb.M{}

// cond holds the comparators for where
var cond []qb.Cmp

// this randomSuffix must be unique . In my application, since I use for loop, I use the for loop key value for this
var randomSuffix int

// key 
var key string

// for `date >= '2019-07-30'
randomSuffix = 0 
key = fmt.Sprintf("%s_%d", "date", randomSuffix) // forms: date_0
cond = append(cond, qb.GtOrEqNamed("date"), key) 
bindMap[key] = 2019-07-30ZGMT // this must be in time.Time. This bindMap key must match the key in your cond

// for `date <= '2019-08-15'`
randomSuffix = 1
key = fmt.Sprintf("%s_%d", "date", randomSuffix)  // forms: date_1
cond = append(cond, qb.GtOrEqNamed("date"), key)
bindMap[key] = 2019-08-15ZGMT // this must be in time.Time. This bindMap key must match the key in your cond

// assign your conditionals to the SelectBuilder
query = query.Where(cond...)

// execute
stmt, names := query.ToCql()
q := gocqlx.Query(s.Session.Query(stmt), names).BindMap(bindMap)
...
```
