### ISSUE TITLE
ExecRelease() has no "not found" error when it used with SELECT statement

### ISSUE THREAD

**Issue by rr32btg** [scylladb/gocqlx#109]
Hello. Sorry for bad English. 

I think I found a bug related to ExecRelease() method:

When I'm trying to execute a SELECT statement with ExecRelease() I haven't received expected "not found" error even if I query empty table. If I change ExecRelease() to GetRelease(&dest) - then I got this error, but in this case, I must allocate and use an unneeded variable. 

ExecRelease together with SELECT query needed at least for check if record exists without creating an extra variable. 

example of broken code:
```go
// this function checks record existance in table
// table_name represents empty table 
func IsExists(NonExistentID string) (bool, error) {

	stmt, names := qb.Select("table_name").Where(qb.Eq("id")).ToCql()
	q := gocqlx.Query(session.Query(stmt), names).BindMap(qb.M{
		"id":     NonExistentID,
	})

	err := q.ExecRelease() //expected to be "not found" error

	if err == nil {
		return true, nil
	}

	if err.Error() == "not found"  {
		return false, nil
	}

	return false, err

}
```

**Comment by dahankzter** [comment]
Gocqlx follows the driver here. The drivers `Exec` doesn't return any error when the empty set is returned either. Sometimes the empty set is just fine and shouldn't be considered an error.
In the case of `GetRelease` you are specifically asking for the scan target to be populated which is impossible in case no data is returned and therefore an error.

Does that make sense?
