### ISSUE TITLE
tokenbuilder for token(column) <= ?

### ISSUE THREAD

**Issue by zwopir** [scylladb/gocqlx#111]
Hi,

I'd like to create the queries used in https://www.scylladb.com/2017/03/28/parallel-efficient-full-table-scan-scylla/ (source code: https://github.com/scylladb/scylla-code-samples/tree/master/efficient_full_table_scan_example_code) via the gocqlx query builder.

As far as I understand, neither the `TokenBuilder` nor the `Cmp` type supports creating a query like
`SELECT ... WHERE token(column) <= ?` and later on binding an int64 token value to the placeholder.

Did I miss something? if not, would you be interested in a PR?

**Comment by zwopir** [comment]
of cause `<=` is just an example for the comparison operator in the above comment

**Comment by mmatczuk** [comment]
@zwopir this is a good idea, currently this is not supported.
I'd suggest you added `EqValue`, `LtValue` and so on functions to the `TokenBuilder`.
I'd be happy to accept the PR, please add tests.
