### ISSUE TITLE
No Not Equal (!=) Comparators

### ISSUE THREAD

**Issue by JoshStrobl** [scylladb/gocqlx#114]
While implementing some `SELECT` queries that required a not equals comparator, I noticed that `qb.Cmp` lacks any Ne* funcs such as:

- `Ne(column string)`
- `NeFunc(column string, fn *Func)`
- `NeLit(column, literal string)` e.g. `column!=literal`
- `NeNamed(column, name string)` e.g. `column!=?`

Usecase: Using a query where you're utilizing a GtOrEqLit comparator however want to ensure you're excluding whatever current row / current item you're referencing, whether you're wanting to make sure you're not returning duplicate articles, messages, etc. posted at or after a certain timestamp micro. Instead you need to do this checking after you get your results.

I believe a Ne operator would be in spec with https://docs.scylladb.com/getting-started/dml/#select-statement per the operators list:

```
operator         ::=  '=' | '<' | '>' | '<=' | '>=' | '!=' | IN | CONTAINS | CONTAINS KEY
```

**Comment by mmatczuk** [comment]
Thanks for reporting @JoshStrobl! Maybe you'd you like to send a PR?

**Comment by mmatczuk** [comment]
Hi @pierDipi, thanks for contribution. Would you mind moving ne code just below eq code?
