### ISSUE TITLE
How to do pagination?

### ISSUE THREAD

**Issue by kabaluyot** [scylladb/gocqlx#125]
How to achieve pagination of results. As of now, my workaround is to fetch all by limit, but manually manage the offset and pagination of response in Go controller.

What is the proper way of handling this in gocqlx query?

**Comment by dahankzter** [comment]
Doesn't `PageSize(n)` on the `*Query` work?
```go
it := gocqlx.Query(session.Query(stmt, 100).PageSize(10), names).Iter()
```

**Comment by dahankzter** [comment]
If you want to actually serve a paged web page then perhaps you can serialize the `PageState` also on the `*Query` and set it every time you paginate but I have personally not tried it out.

**Comment by kabaluyot** [comment]
Haven't seen it in the documentation of `select.go`. Im using the query builder (qb) by the way.

**Comment by mmatczuk** [comment]
Hi @kabaluyot,
query builder is a separate entity. Pagination is a feature of driver.

There are two options:
1. Use iteration like here: https://github.com/scylladb/gocqlx/blob/master/iterx_test.go#L332
2. Use token based pagination like here: https://github.com/scylladb/gocqlx/blob/master/example_test.go#L168

**Comment by kabaluyot** [comment]
Hi @mmatczuk , the first option you presented was using "ALLOW FILTERING" which I think bad for queries fetching just 10 out of thousands rows.

**Comment by mmatczuk** [comment]
It's just in that example you can real all table or partition.
