### ISSUE TITLE
Comment inside CQL always give error: Invalid amount of bind variables

### ISSUE THREAD

**Issue by kokizzu** [scylladb/gocqlx#127]
This query works normally:
```
SELECT * FROM test1 WHERE id = ?; 
```

This query always error: `Invalid amount of bind variables`
```
-- test 123
SELECT * FROM test1 WHERE id = ?; 

// test 123
SELECT * FROM test1 WHERE id = ?; 

/* test 123 */
SELECT * FROM test1 WHERE id = ?; 
```

**Comment by kokizzu** [comment]
I need comments because I have a code that make debugging easier (printing file name and line number inside the CQL as comment, so I can know which CQL causes the error.

**Comment by mmatczuk** [comment]
In general gocql driver (not gocqlx) handles one query at once so you need to chop them on your own. Similar work https://github.com/scylladb/gocqlx/blob/master/migrate/migrate.go#L155.
