### ISSUE TITLE
gocqlx/table/Table support timestamp at the granularity of batch statements

### ISSUE THREAD

**Issue by GingerMoon** [scylladb/gocqlx#136]
I'd like to add some public functions to expose CRUD query builders, just as which is similar as 
func (t *Table) SelectBuilder(columns ...string) *qb.SelectBuilder {
to enable  timestamp at the granularity of batch statements.

Is there any contribution guidance?

**Comment by mmatczuk** [comment]
There is not Contributing.md at the moment. Just send a nice PR :)

**Comment by GingerMoon** [comment]
Here is the [PR](https://github.com/scylladb/gocqlx/pull/137), thanks!
