### ISSUE TITLE
gocqlx/table/Table: support SelectByPartKeyAndSortKey

### ISSUE THREAD

**Issue by GingerMoon** [scylladb/gocqlx#138]
May I create a PR for SelectByPartKeyAndSortKey?

Something like 
func (t *Table) SelectByPartKeyAndSortKey(numSortCols int, columns ...string) (stmt string, names []string) {
    if numSortCols < 1 {
        return "", nil
    }
    stmt, names := qb.Select(t.Metadata().Name).
        Columns(t.Metadata().Columns...).
        Where(getPrimaryKeyCmp(t)[0:numSortCols]...).
        ToCql()
}

**Comment by mmatczuk** [comment]
A better API would be welcome.
How about exporting `PrimaryKeyCmp` ?

**Comment by GingerMoon** [comment]
@mmatczuk Good idea. Here is the PR:
https://github.com/scylladb/gocqlx/pull/139

**Comment by GingerMoon** [comment]
I am thinking, since we have :
// Get returns select by primary key statement.
// Select returns select by partition key statement.
Maybe also it's reasonable to have a similar function like below?
// SelectBy returns select by partition key + sort keys statement.
