### ISSUE TITLE
Support Jaeger wrapper

### ISSUE THREAD

**Issue by SaubereSache** [scylladb/gocqlx#140]
Would it be possible to use an Interface instead of *gocql.Query in gocqlx#Query to support [this](https://github.com/jaegertracing/jaeger/blob/master/pkg/cassandra/gocql/gocql.go)?
It would allow to automatically collect Jaeger spans without much modification to the current code.

**Comment by mmatczuk** [comment]
I think so.

**Comment by mmatczuk** [comment]
[Jaeger interfaces](https://github.com/jaegertracing/jaeger/blob/master/pkg/cassandra/session.go#L70) are very limited, and one must fix jaeger code first to be suitable to work with changed gocqlx.

Gocqlx tries to be transparent so you still can call the gocql.Query methods on Queryx, same rule applies to Iterx.

I'd suggest the following:
- Copy gocql.Query as gocqlQuery interface (all exported methods)
- Copy gocql.Iter as gocqlIter interface (all exported methods)
- Replace all gocql objects with the new interfaces; effectively removing a dependency on gocql :+1:

I like the idea but you need to keep in mind that Jaeger would need to be fixed too to make it work end to end.

Would you  be willing to send a PR @SaubereSache?

**Comment by SaubereSache** [comment]
Will do 👍

**Comment by SaubereSache** [comment]
I did the [modifications](https://github.com/SaubereSache/testing) but I'm currently getting stuck on this error:
``Undefined name user_id in where clause ('user_id = ?')``

Any clue?

**Comment by mmatczuk** [comment]
Maybe this comes from server?

**Comment by SaubereSache** [comment]
Works with normal gocqlx, the query should work.

I also noticed another problem, normal gocql returns a pointer, but the [Interface does not](https://github.com/SaubereSache/gocqlx/blob/9d7d344844e16f02f935c851bc3b868828f5f9f1/queryx.go#L86) since you can't embed a pointer to an interface. => Would break backward compatibility.

**Comment by mmatczuk** [comment]
As long at the query pointer satisfies the interface it's ok to assign, am I missing something?

**Comment by SaubereSache** [comment]
I didn't get it to work as a pointer, maybe I'm missing something but I don't think it works like that

**Comment by mmatczuk** [comment]
The weak point I can see is where it returns iter 

https://github.com/SaubereSache/gocqlx/blob/9d7d344844e16f02f935c851bc3b868828f5f9f1/inter/interface.go#L53

Is that what you mean?

**Comment by SaubereSache** [comment]
The problem is with [this](https://github.com/SaubereSache/gocqlx/blob/9d7d344844e16f02f935c851bc3b868828f5f9f1/queryx.go#L86) since normal gocqlx passes a pointer, but my interface cannot be a pointer (maybe try it out yourself, maybe I'm missing smth)

**Comment by mmatczuk** [comment]
Yes this is what I expected, you need a wrapper to satisfy the interface.

```
func AsQuery(q *gocql.Query) Query {
	return QueryImpl{q}
}

type QueryImpl struct {
	q *gocql.Query
}

func (q QueryImpl) Statement() string {
	panic("implement me")
}

func (q QueryImpl) String() string {
	panic("implement me")
}

func (q QueryImpl) Attempts() int {
	panic("implement me")
}
...
```

So the API could remain unchanged and you could add a version of constructors that accept the new interface.

**Comment by SaubereSache** [comment]
I'm pretty sure I'm already wrapping Session and Query?
https://github.com/SaubereSache/testing/blob/9cd849514f8e0ffcd5bffd9183687d0a0297ec7b/wrapper/wrapper.go#L29
https://github.com/SaubereSache/testing/blob/master/wrapper/clutter.go

**Comment by mmatczuk** [comment]
> I'm pretty sure I'm already wrapping Session and Query?

Correct.

> as you cannot embed a pointer to an Interface into the Queryx struct, but not passing a pointer to the gocqlx#Query function would break backwards compatibility.

Yes the [Queryx constructor](https://github.com/scylladb/gocqlx/blob/master/queryx.go#L93) and friends shall remain unchanged. There should be a separate constructor that accepts interface. The internal representation shall still embed the interface. Note the [Queryx wrapper](https://github.com/scylladb/gocqlx/blob/master/queryx_wrap.go) so return type is always *Queryx.

Having said all of that I had a look at the Jaeger. Correct me if I'm wrong but it looks that this package is intended as a helper for a **storage** backend of Jeager.

If you are interested in tracing Queries like [here](https://github.com/thelastpickle/cassandra-zipkin-tracing) this is not the way to go. [Gocql config](https://godoc.org/github.com/gocql/gocql#ClusterConfig) specifies bunch of **observers** that are typically used for that purpose.

I do not think that this change is actually needed.

**Comment by SaubereSache** [comment]
> Having said all of that I had a look at the Jaeger. Correct me if I'm wrong but it looks that this package is intended as a helper for a storage backend of Jeager.

Correct, I actually didn't notice that. I wanted to modify it as [tracing wrapper](https://github.com/SaubereSache/testing/blob/9cd849514f8e0ffcd5bffd9183687d0a0297ec7b/wrapper/wrapper.go#L33).

> Gocql config specifies bunch of observers that are typically used for that purpose.

That I didn't know, but afaik unusable for tracing as you need to access the context of the previous span (bound to the query using Query#WithContext), which gocql sadly doesn't expose. Also it seems like the observer gets fired once the query finished, but the span needs to get initialized once the query gets executed.

> I do not think that this change is actually needed.

I agree, I'll try my luck with a wrapper around gocqlx, thank you for your help :)

**Comment by mmatczuk** [comment]
Closing this for now.
