### ISSUE TITLE
Supporting Counters

### ISSUE THREAD

**Issue by grossjo** [scylladb/gocqlx#15]
I could not find in the tests or documentations how to update a counter.
Is there support for this yet?

In the meantime, I can write queries using the underlying gocql.

If this feature doesn't exist, I would be interested in adding it.  Counter statements can get quite long written by hand and leveraging the struct binding would be useful.

**Comment by mmatczuk** [comment]
Hi @grossjo 
thanks for the proposal. Counters are not yet supported, I'll try to add that shortly.

**Comment by grossjo** [comment]
Great, let me know if you start the work. 
Incase I find time for me or one of my dev's to add this feature.

**Comment by mmatczuk** [comment]
Sure, it's a small change and good introductory task if you want to help.

Design draft:

Add counters type

```go
type counters strtuct {
    columns columns
    names []string
}
```

Extend `qb.UpdateBuilder` with 

* `counters counters` field
* `Inc(columns string...)` counter `+=1`
* `Incn(columns string...)` counter `+=?`
* `Dec(columns string...)` counter `-=1`
* `Decn(columns string...)` counter `-=?`

Tests.

**Comment by mmatczuk** [comment]
@grossjo fixed by https://github.com/scylladb/gocqlx/pull/16

**Comment by SaubereSache** [comment]
I couldn't find any examples/documentation on how to use this.

May I ask for clarification? The Godocs don't contain any Inc/Dec methods.

**Comment by mmatczuk** [comment]
@SaubereSache yes by means of add https://github.com/scylladb/gocqlx/blob/master/qb/update.go#L153
