### ISSUE TITLE
The version under https://pkg.go.dev/ is still v1.5.0

### ISSUE THREAD

**Issue by kadai0308** [scylladb/gocqlx#153]
Hi, thanks for developing this awesome package.
The version in `https://pkg.go.dev/` is still v1.5.0.
check -> [pkg.go.dev/github.com/scylladb/gocqlx](https://pkg.go.dev/github.com/scylladb/gocqlx@v1.5.0)
So the version is still v1.5 that if I use `go get -u github.com/scylladb/gocqlx`.
Look forward to use `New Session API` from v2.

**Comment by mmatczuk** [comment]
Thanks! Check that out https://pkg.go.dev/github.com/scylladb/gocqlx/v2?tab=doc
