### ISSUE TITLE
LWT support for INSERTS

### ISSUE THREAD

**Issue by dahankzter** [scylladb/gocqlx#158]
Maybe I am missing how to do it but I can't see a way to execute

`INSERT INTO .... IF NOT EXISTS`

using the insert builder at the moment.

**Comment by zimnx** [comment]
There's Unique method.
https://github.com/scylladb/gocqlx/blob/ae6d066255b6c77ee5985892163452e98469903f/example_test.go#L657

**Comment by dahankzter** [comment]
Great!
