### ISSUE TITLE
Why is [Query(q *gocql.Query, names []string) *Queryx ] depreciated?

### ISSUE THREAD

**Issue by GingerMoon** [scylladb/gocqlx#161]
May I know why is [Query(q *gocql.Query, names []string) *Queryx ] depreciated?
How about Queryx? 
What is the problem of using it?
```
Query(q *gocql.Query, names []string) *Queryx
```

**Comment by GingerMoon** [comment]
Sorry that I thought I should use gocql.Session API....
```
// Deprecated: Use Session API instead.
func Query(q *gocql.Query, names []string) *Queryx {
```

**Comment by GingerMoon** [comment]
Anyway, I would appreciate if anyone could tell me if there is any problem if keep using the deprecated API so that I can decide whether I should modify my existing code or not.

**Comment by mmatczuk** [comment]
New code (using v2 of gocqlx) should use session API it's much more convenient.
