### ISSUE TITLE
support for Statement request size

### ISSUE THREAD

**Issue by tarzanek** [scylladb/gocqlx#169]
Java driver has requestSizeInBytes
to give a higher estimate of Statement size for counting the batch size
https://docs.datastax.com/en/drivers/java/3.7/com/datastax/driver/core/Statement.html#requestSizeInBytes-com.datastax.driver.core.ProtocolVersion-com.datastax.driver.core.CodecRegistry-

go has only Batch::Size() 

so when client wants to do exact batch splitting, it's hard to count the statement size

Could above be ported over from java to go?

Java logic is in:
https://github.com/scylladb/java-driver/blob/3.7.1-scylla-2/driver-core/src/main/java/com/datastax/driver/core/BatchStatement.java#L203
or
https://github.com/scylladb/java-driver/blob/3.7.1-scylla-2/driver-core/src/main/java/com/datastax/driver/core/RegularStatement.java#L185
or
https://github.com/scylladb/java-driver/blob/3.7.1-scylla-2/driver-core/src/main/java/com/datastax/driver/core/BoundStatement.java#L307
(and similar, just query java driver tree for requestSizeInBytes)

**Comment by dahankzter** [comment]
Perhaps this belongs in the driver? Not sure what is needed is available
outside of the driver package.

**Comment by tarzanek** [comment]
closing in favour of https://github.com/scylladb/gocql/issues/51
