### ISSUE TITLE
Mocking Gocqlx calls

### ISSUE THREAD

**Issue by shivajividhale** [scylladb/gocqlx#172]
Hi folks,

I've been using Gocqlx for querying Cassandra DB. I'm just curious to know if Gocqlx calls can be mocked. I could see the example in https://github.com/scylladb/gocqlx/blob/master/example_test.go. However, the test file seems to be interacting with a Cassandra instance locally. Is there a way to mock some of the calls such as `
```
var someTable = table.New(someMetaData)
q := session.Query(someTable.Select()).BindStruct()
q.ExecRelease()
```

I have also gone through https://github.com/gocql/gocql/issues/415#issuecomment-277530829 this. But not sure this would help me since I'm now using `gocqlx` and not `gocql`

**Comment by mmatczuk** [comment]
Those are not interfaces so I would say no. If you want to do the mocking like that I'd say adding a mockable data access layer is a way to go. Still I do not think this is such a great idea.

**Comment by Guilospanck** [comment]
Hi,
I've stumble across this issue and created some wrapper around the library.
You can check it out at [igocqlx](https://github.com/Guilospanck/igocqlx) and [gocqlxmock](https://github.com/Guilospanck/gocqlxmock).

Also, if you wanna more information about how to use it than there are inside the README, you can check [this repository](https://github.com/Guilospanck/scylladb-and-go) which makes use of both of them.

Feel free to comment or help with it!
Cheers

**Comment by mmatczuk** [comment]
Nice @Guilospanck
