### ISSUE TITLE
Support for Composite PartKey

### ISSUE THREAD

**Issue by pilayar76** [scylladb/gocqlx#175]
I have a table called order_fullfillment_status.

```
CREATE TABLE test.order_fullfillment_status(
order_id text,
order_fullfillment_id text,
status_arr set<frozen<order_status_obj>>,
PRIMARY KEY (order_id,order_fullfillment_id))
WITH comment = 'to store order fullfillment status details';
```

Can anyone help me to derive schema for this in terms table.Metadata as it uses, composite primary key. PartKey is taken as string in the code.

**Comment by zimnx** [comment]
@pilayar76 [table.Metadata.PartKey](https://github.com/scylladb/mermaid/blob/master/vendor/github.com/scylladb/gocqlx/v2/table/table.go#L18) is a slice of strings, you should assign `[]string{"order_id","order_fullfillment_id"}`.

**Comment by pilayar76** [comment]
Thanks for the quick response. @zimnx 

Still facing the same issue. Attaching the snippet for reference.

`type OrderFullfilment struct {
	OrderID            string        `db:"order_id"`
	OrderFullfilmentID string        `db:"order_fullfillment_id"`
	StatusArr          []interface{} `db:"status_arr"`
}

// metadata specifies table name and columns it must be in sync with schema.
var OrderFullfilmentMetadata = table.Metadata{
	Name:    "order_fullfillment_status",
	Columns: []string{"order_id", "order_fullfillment_id", "status_arr"},
	PartKey: []string{"order_id,order_fullfillment_id"},
	SortKey: []string{"order_fullfillment_id"},
}

// personTable allows for simple CRUD operations based on personMetadata.
var OrderFullfilmentTable = table.New(OrderFullfilmentMetadata)`

`var orderFullfilment []models.OrderFullfilment
	q := session.Query(models.OrderFullfilmentTable.Select()).BindMap(qb.M{"order_id": "12345", "order_fullfillment_id": "12345-01"})
	if err := q.SelectRelease(&orderFullfilment); err != nil {
		log.Printf("Error while getting all todos, Reason: %v\n", err)
	}`

Error:

`Reason: bind error: could not find name "order_id,order_fullfillment_id" in map[string]interface {}{"OrderFullfilmentID":"12345-01", "OrderID":"12345"}`

**Comment by mmatczuk** [comment]
The db tags are not needed and I think they are wrongly set because it complains not to be able to find `order_id,order_fullfillment_id` string in the map.

**Comment by pilayar76** [comment]
Removed the DB thing and still facing the same issue. Not sure if Composite primary key is support or not. As I can see in the code, PartKey is considered as string not as interface.

**Comment by mmatczuk** [comment]
The issue is here `PartKey: []string{"order_id,order_fullfillment_id"},`

**Comment by pilayar76** [comment]
How to configure a composite key in Models?

**Comment by mmatczuk** [comment]
Like any other string slice `PartKey: []string{"order_id", "order_fullfillment_id"},`

**Comment by pilayar76** [comment]
Have changed that as well... Still facing issues...

`var OrderFullfilmentMetadata = table.Metadata{
	Name:    "order_fullfillment_status",
	Columns: []string{"order_id", "order_fullfillment_id", "status_arr"},
	PartKey: []string{"order_id", "order_fullfillment_id"},
	SortKey: []string{"order_fullfillment_id"},
}`

`Reason: bind error: could not find name "order_fullfillment_id" in map[string]interface {}{"order_id":"12345"}`

**Comment by pilayar76** [comment]
Finally, I have got this working but while printing the result, getting the below error. Can you please help @mmatczuk 

I have got 3 columsn x,y,z where z is UDT. to which I have defined a struct gocqlx.UDT.

`EXTRA string=expected 1 column in result while scanning scannable type slice but got 3`

**Comment by pilayar76** [comment]
@mmatczuk  - Thanks for the support. i have solved this.

Problem was using UDT and gocqlx.UDT was not working (not sure why), then cql keyword worked.

Closing this ticket.
