### ISSUE TITLE
Is it possible to create a `uid IN (?)` query with `BindStruct` ?

### ISSUE THREAD

**Issue by Elojah** [scylladb/gocqlx#182]
I'm trying to execute a query like
`SELECT uid FROM main.foo WHERE uid IN (?)`
and i'd like to associate this to `BindStruct`, is it possible ?

I tried using a struct with `UID []uuid` field but gocqlx doesn't translate it into a `IN` query.

Thanks

**Comment by mmatczuk** [comment]
Looks similar to https://github.com/gocql/gocql/issues/166. 
Yes it is supported and should work, use `qb.In` function.

**Comment by Elojah** [comment]
Didn't found this issue (`IN` keyword hard to search...), thank for your answer and indications
