### ISSUE TITLE
auth with TransitionalAuthenticator

### ISSUE THREAD

**Issue by rizzi37** [scylladb/gocqlx#184]
```
cluster := gocql.NewCluster([]string{"127.0.0.1:9042", "127.0.0.1:9043", "127.0.0.1:9044"}...)
		cluster.Authenticator = gocql.PasswordAuthenticator{
			Username: "cassandra",
			Password: "cassandra",
		}
```

some error with : scylladb connect gocql: unable to create session: unable to discover protocol version: unexpected authenticator "com.scylladb.auth.TransitionalAuthenticator"

can not login. i must create other super user ?

**Comment by mmatczuk** [comment]
The TransitionalAuthenticator is not supported in gocql, https://github.com/scylladb/gocql/issues/76.

**Comment by mmatczuk** [comment]
@rizzi37 try running with gocql updated to https://github.com/scylladb/gocql/commit/428d676d679ca4390d86a15bac6c0315acf70f40

**Comment by mmatczuk** [comment]
cc @amoskong

**Comment by rizzi37** [comment]
fine. thx @mmatczuk

**Comment by amoskong** [comment]
> @rizzi37 try running with gocql updated to [scylladb/gocql@428d676](https://github.com/scylladb/gocql/commit/428d676d679ca4390d86a15bac6c0315acf70f40)

Thanks, I will test the fix
