### ISSUE TITLE
Table GetQuery() comment wrong

### ISSUE THREAD

**Issue by Alfa-Alex** [scylladb/gocqlx#189]
The comment of Table.GetQuery says:
```
// GetQuery returns query which gets by partition key.
```
This is in [this line](https://github.com/scylladb/gocqlx/blob/01be91c745c4563913e560ff27b7991aa411b149/table/table.go#L95).

However, this func calls `t.Get()`, which has the following comment:
```
// Get returns select by primary key statement.
```
(see [this line](https://github.com/scylladb/gocqlx/blob/01be91c745c4563913e560ff27b7991aa411b149/table/table.go#L83))

The latter is right, so the comment of the first func should be fixed so correctly speak of the `primary key`, not the `partition key`.

**Comment by mmatczuk** [comment]
Correct. @Alfa-Alex please take a credit for it by sending a patch.

**Comment by alfa-alex** [comment]
I realized I forgot to fix the comment of the corresponding `GetQueryContext` function. Since this has been confusing me quite some times now, I propose to fix this. PR [here](https://github.com/scylladb/gocqlx/pull/257).
