### ISSUE TITLE
Add named limit to QueryBuilder

### ISSUE THREAD

**Issue by kjaksik** [scylladb/gocqlx#191]
Hi guys,
I was wondering if there is a possibility of adding an option to add named limit to query builder?
Currently, we can only use the `Limit` function and it injects the limit parameter directly into the statement.

**Comment by aszecowka** [comment]
A little bit of context: we calculate the limit dynamically and because of that we generate many prepared statements that differs only in the LIMIT.

**Comment by mmatczuk** [comment]
Could you send a patch that adds `LimitNamed` function?
