### ISSUE TITLE
Delete Allow Filtering

### ISSUE THREAD

**Issue by jtcarnes** [scylladb/gocqlx#197]
Current DeleteBuilder does not have an allow_filter option to enable the filtering flag on delete queries.

**Comment by mmatczuk** [comment]
Thanks reporting. Would you mind sending a patch?

**Comment by slivne** [comment]
Afaik this is not possible in cql

Can you please provide a sample and show that it works

**Comment by jtcarnes** [comment]
Sorry, I've been away. Ah, I see what you mean. I was originally getting the 'must allow filtering' error message (was deleting using a range with a non-partition or clustering key). Sorry for the noise! 

For anyone that has a similar error message and is looking for an answer, the only way in CQL to do this would be to use the `IF` clause of a delete statement or to properly define your clustering keys to allow deletes on a range.
