### ISSUE TITLE
when use goroutine prepared cql not worked like get query

### ISSUE THREAD

**Issue by rizzi37** [scylladb/gocqlx#198]
for example when oder get , the first query will prepared use 3ms, and other will 1ms,

when goroutine, cold every query cost 3ms, the prepared cql not woked. only when get one row make the cql prepared ready.

**Comment by rizzi37** [comment]
it's like Hotspot Invalid

**Comment by mmatczuk** [comment]
Hey.

The issue is related to the [gocql](https://github.com/gocql/gocql) driver and it's automated query preparation.
You need to elaborate on the issue you are facing because it's unclear what happens.

**Comment by rizzi37** [comment]
ok, i open in gocql issue and close here,THX
