### ISSUE TITLE
using of gocql.UnsetValue

### ISSUE THREAD

**Issue by N1cOs** [scylladb/gocqlx#202]
Hi everyone! Recently we faced a following problem. In one of our processes we create a query by specifying ALL columns of a model struct and bind its fields by using method `BindStruct`. Some of the struct fields can be `nil` values and it leads to the problem that we generate ton of tombstones by explicitly sending `null` values to Cassandra. Base driver `gocql` has `gocql.UnsetValue` for unsetting value in statements that are already prepared. Unfortunately, creating custom type and adding method `gocql.MarshalCQL` doesn't solve the problem because `gocql` has different logic for set and unset values: we have to pass `gocql.UnsetValue` directly into `query.Bind` method.

To solve this problem we have some suggestions:
* Add method like `NilAsUnset` for `Queryx` struct. It sets some flag and then method `bindStructArgs` binds `gocql.UnsetValue` for all `nil` fields.
* Add interface with one method `BindCQL() interface{}`. Then in binding process check if value implements this interface. For these fields, instead of themselves, bind a return value of `BindCQL` method. As a result clients have flexibility in defining situations when custom fields should be considered as unset.

What do you think guys? Can we workaround stated problem without adding new functionality? If it's impossible, then we're ready to implement any of the suggested methods by ourselves.

**Comment by mmatczuk** [comment]
Overall the proposal makes sense.

Ad 1.
This can be added on iterator level if needed similar to [Unsafe](https://github.com/scylladb/gocqlx/blob/979397bc5ea0e5b37559b33ef02b7e1e144d0b50/iterx.go#L38).

Ad 2.
I'd rather add that as a new option in the `db` tag.

**Comment by N1cOs** [comment]
@mmatczuk 
1. Actually I don't get the proposal about adding it on iterator level. How we can do it for execute queries? Can you please give here a small example?
2. What kind of option it can be? Like `omitempty` in json package?

**Comment by mmatczuk** [comment]
Correct and  correct.

**Comment by N1cOs** [comment]
Ok, so I have the following plan:
* I'll rewrite function `bindStructArgs`. Apparently I need to unwrap function `mapper.TraversalsByNameFunc`, cause I need options from `FieldInfo` struct.
* During traversal I'll check if value is empty and field has tag `unsetempty`, then I'll bind `gocql.UnsetValue`
* Add subtest for empty values in `TestQueryxBindStruct` function
* Add some examples

@mmatczuk is it ok?

**Comment by mmatczuk** [comment]
I want to avoid taxing the main flow with more reflection and keep it simple in general.

I had a look in the code. We could a decorator in Query, if the decorator is set call the decorator on bind.

```go
type Queryx struct {
...
	Transformer func(name string, val interface{}) interface{}
```

then `bindStructArgs` goes to Queryx and if Transformer is not nil it's called before adding to args list.

On top of that you can build the UnsetValue transformer.

**Comment by N1cOs** [comment]
I see your point but for me is not clear how to get info about tags in such transformer method. If we discard idea about using tags, then I understand how to do it. To be more json-like and use tags we can implement the following transformer method:
```go
type tranformerFn func(fi *reflectx.FieldInfo, val interface{}) interface{}
```
And then rewrite `bindStructArgs` method:
```go
tm := m.TypeMap(v.Type())
for i, name := range names {
	fi, ok := tm.Names[name]
	if ok {
		val := reflectx.FieldByIndexesReadOnly(v, fi.Index).Interface()
		if tf != nil { // transformerFn
			val = tf(fi, val)
		}
		arglist = append(arglist, val)
	}
}
```
As you can see I made `tranformerFn` as private, because it's low-level for outside clients.

**Comment by mmatczuk** [comment]
The point is you do not need the tags. 
The name and value in the context of a query is enough - the implementation will be simpler.

**Comment by N1cOs** [comment]
Ok, got it. I will make a pr in several days
