### ISSUE TITLE
Return updated values after executing `Update` query

### ISSUE THREAD

**Issue by JonasHiltl** [scylladb/gocqlx#222]
Hello, is it possible to return the updated row values after calling an `Update` query?
I tried searching through the repo but couldn't find a hint showing if this can be done.

This is how I build my update statement. Maybe it is possible to do something similar to `GetRelease(&result)`, just for an update statement.
```go
func (pq *partyQuery) Update(ctx context.Context, p datastruct.Party) (datastruct.Party, error) {
	var result datastruct.Party
	b := qb.
		Update(TABLE_NAME).
		Where(qb.Eq("id"))

	if p.Title != "" {
		b.Set("title")
	}

	b.If(qb.Eq("user_id"))
	stmt, names := b.ToCql()

	err := pq.sess.Query(stmt, names).
		BindMap((qb.M{"id": p.Id, "title": p.Title, "user_id": p.UId})).
		ExecRelease()
	if err != nil {
		return datastruct.Party{}, err
	}

	return result, nil
}
```

**Comment by mmatczuk** [comment]
This is not how LSM based databases work, there is not read before write.
If you need this kind of functionality you need to implement it in the app.

**Comment by JonasHiltl** [comment]
Ok, thanks for clarifying.
