### ISSUE TITLE
Health check for cassandra

### ISSUE THREAD

**Issue by CarloDeVita** [scylladb/gocqlx#227]
Hi,
It would be nice to have some function to check cassandra liveness (session.Ping() as an example).
If I am not wrong, it still does not exist for gocql / gocqlx. Am I missing something? 
What do you think about adding this feature? 

Thanks,
Carlo

**Comment by mmatczuk** [comment]
Scylla Manager implements Ping. It is a driver feature I do not think it really fits here.
