### ISSUE TITLE
Upgrade to Go 1.18

### ISSUE THREAD

**Issue by osodracnai** [scylladb/gocqlx#230]
is there any plan to update the project to go 1.18?

**Comment by mmatczuk** [comment]
You can use it with go 1.18 no problem.
Or you mean something else?

**Comment by osodracnai** [comment]
i meant upgrade the go.mod file to 1.18 version

**Comment by mmatczuk** [comment]
What's the benefit?

**Comment by osodracnai** [comment]
mainly generics and fuzz testing

**Comment by mmatczuk** [comment]
What's the benefit for gocqlx of just bumping a string in go mod?

**Comment by osodracnai** [comment]
So people could use new features to contribute into the project instead of being held by a string on go.mod

**Comment by kaatinga** [comment]
I reckon it will have sense after 1.17 is not used anymore. Now lots of services in production still use go 1.17.
