### ISSUE TITLE
Fix linter in GH action

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/gocqlx#232]

**Comment by MrWormHole** [comment]
I can actually fix that, it is caused by implicit install of Go 1.18 for golangci-lint which enabled implicit latest Go install on v2, you have to update to v3 :) have a look at this lovely thread :) https://github.com/golangci/golangci-lint-action/issues/434

**Comment by MrWormHole** [comment]
I can actually fix that, it is caused by implicit install of Go 1.18 for golangci-lint which enabled implicit latest Go install on v2, you have to update to v3 :) have a look at this lovely thread :) https://github.com/golangci/golangci-lint-action/issues/434

**Comment by mmatczuk** [comment]
We need to configure the new linter.

**Comment by MrWormHole** [comment]
@mmatczuk I mean I can do that if you want?? but the question is how many of them are developer errors and how many of them are linter errors? is a process for those, you want me to look into?

**Comment by MrWormHole** [comment]
what my suggestion would be is to go for 1.38.0 rather than the latest v1.45.2 @mmatczuk this will be less linter errors, then we can either put .golangci.yml which adjusts the linter settings for you or we fix the developer issues around default settings of 1.38.0
