### ISSUE TITLE
Select query with IN and Boolean List does not return row

### ISSUE THREAD

**Issue by JonasHiltl** [scylladb/gocqlx#235]
I have the Schema below which represent friend relations between two users.
```
CREATE TABLE IF NOT EXISTS friend_relations (
    user_id text,
    friend_id text,
    accepted boolean,
    requested_at timestamp,
    accepted_at timestamp,
    PRIMARY KEY (user_id, accepted, friend_id)
);
```
With this Schema I can get all friends of a user, by just querying for the `user_id`. I can also only get the accepted friends of a user by filtering with the `accepted` column. I also hoped to get the relation between two users by specifying a `user_id`, a `friend_id` and also filter `accepted` through an `IN` query with just a list of `[true, false]` which should get me the friend relation between two users either if it is accepted or not.

This is how I built and executed the query with `gocqlx`:
```go
stmt, names := qb.
	Select(FRIEND_RELATIONS).
	Columns(friendRelationMetadata.Columns...).
	Where(qb.Eq("user_id")).
	Where(qb.In("accepted")).
	Where(qb.Eq("friend_id")).
	ToCql()

err = r.sess.
	Query(stmt, names).
	BindMap((qb.M{"user_id": uId, "friend_id": fId, "accepted": []bool{false, true}})).
	GetRelease(&res)
```
The `stmt` created is 
```
SELECT user_id,friend_id,accepted,requested_at,accepted_at FROM friend_relations WHERE user_id=? AND accepted IN ? AND friend_id=?
```
If I run the query with cqlsh and sample data I get the correct row returned:
```
$ SELECT user_id,friend_id,accepted,requested_at,accepted_at FROM friend_relations WHERE user_id='2AGCWHQDrTzEttHI1ihprHpm7cO' AND accepted IN (false,true) AND friend_id='2AGCZUmQkt8MkIOykZKWH6xi6f5';

 user_id                     | friend_id                   | accepted | requested_at                    | accepted_at
-----------------------------+-----------------------------+----------+---------------------------------+-------------
 2AGCWHQDrTzEttHI1ihprHpm7cO | 2AGCZUmQkt8MkIOykZKWH6xi6f5 |    False | 2022-06-07 18:30:27.959000+0000 |
```
But when I run it with `gocqlx` I get the Error `not found`. My guess would be that the `[]bool{false, true}` list does not get marshalad into `(false,true)` like I did with `cqlsh`.

**Comment by mmatczuk** [comment]
That's kind of interesting, looks more like gocql issue on the 1st sight. BTW why not check accepted != null?

**Comment by mmatczuk** [comment]
Can you test that with raw gocql?

**Comment by JonasHiltl** [comment]
So I tried it again and it actually wasn't caused by the boolean array, I just swapped the `friend_id` and `user_id` on accident and that's why the row was not returned.

But I also tried searching with `accepted != null` and got the error:
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Unsupported "!=" relation: accepted != null"
```
Is `!=` not supported for booleans or even in general?

**Comment by mmatczuk** [comment]
I guess it's not supported.
