### ISSUE TITLE
[ASK]: Prepare Statement With Table Metadata

### ISSUE THREAD

**Issue by rizaldirnm** [scylladb/gocqlx#241]
I am using Table Metadata to perform query to Scylladb.
The code something like

```
qx := table.SelectQueryContext().BindStruct()

qx.SelectRelease(&dest)
```

Do they perform Prepare Statement automatically?

Iam using `gocqlx v2.7.0`

Thank you in advance!

**Comment by zimnx** [comment]
Yes, gocql underneath prepares every query and caches it.
