### ISSUE TITLE
Prepared statements

### ISSUE THREAD

**Issue by Hammad1029** [scylladb/gocqlx#266]
Does this package support preparing statements like drivers in other languages for scylla? for e.g java: https://java-driver.docs.scylladb.com/scylla-3.7.2.x/manual/statements/prepared

EDIT: I am talking about in both cases: queries generated by the ORM and string queries executed using session.ExecStmt

**Comment by sylwiaszunejko** [comment]
GocqlX uses gocql underneath and gocql automatically prepares DML queries (SELECT/INSERT/UPDATE/DELETE/BATCH statements) and maintains a cache of prepared statements (documentation: https://pkg.go.dev/github.com/gocql/gocql#hdr-Prepared_statements).
