### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by izenhaim** [scylladb/gocqlx#267]
Hi, just wanted to ask about the plans to release a new version. 
Since batchx isn't available on 2.8.0 I have had to use the master branch in my go.mod.
would be great if you could release a new version. 
many thanks.

**Comment by mykaul** [comment]
The diff is quite small - https://github.com/scylladb/gocqlx/compare/v2.8.0...master - are you missing something specific?

**Comment by izenhaim** [comment]
yes, the batch wrapper with BindStruct.

**Comment by sylwiaszunejko** [comment]
A new major release is now available.
