### ISSUE TITLE
Add linter to CI

### ISSUE THREAD

**Issue by sylwiaszunejko** [scylladb/gocqlx#270]
There is a need for a linter in CI. We should try to add https://github.com/dominikh/go-tools to CI here

**Comment by mykaul** [comment]
We can start with 'go vet' just as we do @ gocql -  https://github.com/scylladb/gocql/blob/6663620992a81d532f3d98248b5ccfe018dd1c38/.github/workflows/main.yml#L27C14-L27C20  ...
