### ISSUE TITLE
is there alternative to used in rust 

### ISSUE THREAD

**Issue by ikaasraa** [scylladb/gocqlx#281]
hello ...
is there an alternative to used in rust project ?? or anyone know about a good example with best practice for rust project

**Comment by sylwiaszunejko** [comment]
@wprzytula Could you answer that?

**Comment by wprzytula** [comment]
I don't understand the question. How should I parse it?
Is `used` some keyword in Rust driver or gocqlx?

**Comment by sylwiaszunejko** [comment]
@ikaaasra

**Comment by wprzytula** [comment]
So is the question about a `gocqlx` equivalent for Rust projects?
If so, then there is e.g. [charybdis](https://github.com/nodecosmos/charybdis).

**Comment by dkropachev** [comment]
Question is answered, closing it.
