### ISSUE TITLE
V3 breaks "go install" and "go run"

### ISSUE THREAD

**Issue by alfa-alex** [scylladb/gocqlx#287]
Up to V2, it was very handy to be able to run, e.g., the `schemagen` tool with `go run` (`go run github.com/scylladb/gocqlx/v2/cmd/schemagen@latest`) or to install it with `go install`.

Since V3, this is no longer possible, as `go` would complain:
```
go: github.com/scylladb/gocqlx/v3/cmd/schemagen@latest (in github.com/scylladb/gocqlx/v3@v3.0.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

This is specified in https://github.com/golang/go/issues/40276:
> If that module has a go.mod file, it must not contain directives that
would cause it to be interpreted differently if the module were the main
module. In particular, it must not contain replace or exclude
directives.

(A longer discussion about this can be found in [this issue](https://github.com/golang/go/issues/44840).)

Thus, the reason for this to occur in the case of `gocqlx` is the `replace` directive that was added in `v3`:
```go.mod
replace github.com/gocql/gocql => github.com/scylladb/gocql v1.14.0
```

I want to raise awareness of this, as the ability to run `schemagen` with `go run` (or install it with `go install`) has been very useful to me.

Unfortunately, I cannot propose an immediate mitigation of this issue (other than replacing all imports to use the `scylladb/gocql` module directly).

**Comment by sylwiaszunejko** [comment]
Unfortunately for now there is no way to use `scylladb/gocql` in the imports, see the discussion here: https://github.com/scylladb/gocql/issues/161. Changing module name for `scylladb/gocql` is a breaking change so it would require major release in `scylladb/gocql` repo, but this would not happen soon, here is the issue for changes that require new version release https://github.com/scylladb/gocql/issues/232. 

Unfortunately I do not have any quick workaround to make using `go install` possible @dkropachev any thoughts?

**Comment by dkropachev** [comment]
@alfa-alex , Thanks for bringing this to our attention, unfortunately, it won't go away until https://github.com/scylladb/gocql/issues/232 is merged and we need at least a year to make it happen.
Luckily there is a workaround:
```
git clone git@github.com:scylladb/gocqlx.git`
cd gocqlx/cmd/schemagen/
go install .
```

**Comment by dkropachev** [comment]
I am closing it, but feel free to ask more questions or even reopen it.
