### ISSUE TITLE
[QUESTION] multiple pods applying migrations

### ISSUE THREAD

**Issue by izenhaim** [scylladb/gocqlx#296]
Hi, I have added applying migrations at the start of my project. when multiple pods start at the same time, can this lead to a conflict?

**Comment by izenhaim** [comment]
Sure, for example i have a new migration dropping a column. My k8s maxSurge is 3, so 3 new pods come up, all of them try to apply migrations. what I understood from the code is that they would all List db migrations and this could lead to all of them trying to execute the migration (when migration is completed then db info is created, so they would all think they need to apply the migration). I can't think of a scenario that causes serious problems, but in case of dropping a column, one pod would succeed and others would get error and restart. next time they would be fine. but I can't be sure there is not a scenario causing schema problems for Cassandra.

**Comment by dkropachev** [comment]
maxSurge for pods where migrations is ran ?

**Comment by izenhaim** [comment]
I'm thinking of moving it to CI/CD , but this was my initial plan when I thought of this problem.

**Comment by dkropachev** [comment]
You need to move it to a separate deployment or task since you may want to have many nodes, but migration needs to be run once
