### ISSUE TITLE
Add a code generator that would extract tables and columns from a database

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/gocqlx#4]
## Flags
We need pretty much all the flags from https://github.com/volatiletech/sqlboiler#initial-generation, schema should be replaced with keyspace and models should be written to models/keyspace.

## Output
For every table in a given keyspace generate Table metatata.

```go
// TableName is generated metadata for <keyspace>.<table_name>.
struct TableName {
    Keyspace string
    Name string
    PK string[]
    Columns string[]
    ColumnName string
    ...
}
```

We shall follow the golang naming conventions and snake_case table / column names should be converted to camel case.

**Comment by mmatczuk** [comment]
Cluster connectivity flags should be compatible with https://github.com/gocql/gocql/blob/master/common_test.go#L15.

**Comment by SaubereSache** [comment]
I'd really appreciate an implementation of this as it removes a lot of boilerplate code

**Comment by mmatczuk** [comment]
Any volunteers?

**Comment by Bobochka** [comment]
Is it something like https://github.com/Bobochka/gocqlxschemagen that you looking for? If yes, how do you see the integration, should it be a separate bin inside this repo?

**Comment by mmatczuk** [comment]
Nice work thanks.

Let's have a `cmd/schemagen` and put it there.

It would be nice to:
* put template to a separate file and embed it
* have an integration test 
* update readme
* provide example(s)

**Comment by Bobochka** [comment]
@mmatczuk https://github.com/scylladb/gocqlx/pull/201

**Comment by mmatczuk** [comment]
Fixed.
