### ISSUE TITLE
Implement TTL() for UpdateBuilder

### ISSUE THREAD

**Issue by SpiritOfWill** [scylladb/gocqlx#40]
Add `func (b *InsertBuilder) LitTTL(ttl uint32) *InsertBuilder {}` method.

According to https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateTable.html#tabProp__cqlTableDefaultTTL, the maximum value for TTL `630720000` (20 years), so uint32 will be enough.

Because now, for setting TTL we need to do a lot of code for converting structs into the map, setting hardcoded `_ttl` value and use `BindMap()` instead of `BindStruct()`:
```
        ...

	values["_ttl"] = someVar
	stmt, names := qb.Insert(GetTableName()).Columns(fields...).TTL().ToCql()
	query := gocqlx.Query(GetQuery(), names).BindMap(values)

        ...
```
and we don't want to update our struct with TTL field.

**Comment by SpiritOfWill** [comment]
@mmatczuk, what do you think about this? Can I implement this?

**Comment by mmatczuk** [comment]
One of design goals here was to promote usage of prepared statements, however, I'm not very happy whit how this is done now. How about we introduce 

* `func (b *UpdateBuilder) TTL(ttl int)`
* `func (b *UpdateBuilder) TTLNamed(name string)`
* `func (b *UpdateBuilder) Timestamp(t time.Time)`
* `func (b *UpdateBuilder) TimestampNamed(name string)`

(same for InsertBuilder)

The named variants would enable user to provide a custom binding name.

This should be implemented by changing `using` [1]. I think it must be more sophisticated and when you set a name the value should be cleared and vice versa. We can use helper function [2] or even inline and delete them (maybe?).

[1] https://github.com/scylladb/gocqlx/blob/master/qb/expr.go#L22
[2] https://github.com/scylladb/gocqlx/blob/master/qb/utils.go#L25

**Comment by mmatczuk** [comment]
Ad 1. It's OK for this change to break backwards compatibility because the benefits are greater than the costs. I do not think that TTL would hit much users, and migration path is trivial. 

Ad 2. We can go with int32

As a side comment for Timestamp please marshall it as ISO 8601 [1] 

[1] https://docs.datastax.com/en/cql/3.3/cql/cql_reference/timestamp_type_r.html

**Comment by SpiritOfWill** [comment]
OK.
One more question: shouldn't it be `TTLNamed(name string)`

**Comment by SpiritOfWill** [comment]
@mmatczuk, OK.

**Comment by SpiritOfWill** [comment]
@mmatczuk, does this `USING TIMESTAMP ? AND TTL ?` really works together in Cassandra?
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlInsert.html
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlUpdate.html

**Comment by mmatczuk** [comment]
@SpiritOfWill the real docs are here https://cassandra.apache.org/doc/latest/cql/dml.html#insert as you can see it's 

>  [ USING update_parameter ( AND update_parameter )* ]

Please double check that.

**Comment by SpiritOfWill** [comment]
@mmatczuk, OK, sorry.

**Comment by mmatczuk** [comment]
Maybe it's not supported by DataStax LOL

**Comment by mmatczuk** [comment]
@SpiritOfWill any update on that?

**Comment by SpiritOfWill** [comment]
@mmatczuk hi, sorry, got a lot of work to do.
