### ISSUE TITLE
cql where expression

### ISSUE THREAD

**Issue by engin** [scylladb/gocqlx#47]
hello,

is there any way to use `qb` to generate `expr` ?

example:
```
	SELECT * FROM users WHERE expr(users_index, '{
		filter: {
		   type: "boolean",
		   must: [
			  {type: "wildcard", field: "name", value: "*a"}
		   ]
		}
	 }')
```

**Comment by mmatczuk** [comment]
We implement https://cassandra.apache.org/doc/latest/cql/dml.html#grammar-token-where_clause. You can use query compilation https://github.com/scylladb/gocqlx/blob/master/example_test.go#L198
