### ISSUE TITLE
Queryx GetRelease() with interface{}

### ISSUE THREAD

**Issue by Linuturk** [scylladb/gocqlx#73]
I've written a database package for interfacing with Cassandra, and I'm attempting to replace gocql with gocqlx inside that package.

My package has a Table type that has various methods on the Table, like SelectOne, SelectAll, InsertOne, etc.

In a leaf package, I'm calling my library like this:
```
uuid gocql.UUID
f MyCustomStruct
// SelectOnex func(value interface{}, dest interface{}) error
	err := MyTable.SelectOnex(uuid, f)
	if err != nil {
		return err
	}
```

Inside my database package this function looks like this:
```
func (t Table) SelectOnex(value interface{}, dest interface{}) error {

	// build our statement
	stmt, names := qb.Select(t.FullName()).Where(qb.Eq(t.PrimaryKey)).ToCql()

	// build our query object
	q := gocqlx.Query(Session.Query(stmt), names).BindMap(qb.M{t.PrimaryKey: value})

	// execute the query
	if err := q.GetRelease(dest); err != nil {
		return err
	}

	return nil
}
```

Unfortunately, it seems that the `q.GetRelease(dest) doesn't like the interface{} type coming from my wrapped function. `scannable dest type interface with >1 columns (7) in result`

Is there a way to pass my MyCustomStruct type through so that it is properly decoded into?

**Comment by Linuturk** [comment]
One additional detail.

When I move the SelectOnex code directly into the package consuming my database package, the function GetRelease() works as expected.

```
func (f *MyCustomStruct) GetOne(uuid gocql.UUID) error {

	// build our statement
	stmt, names := qb.Select(MyTable.FullName()).Where(qb.Eq(MyTable.PrimaryKey)).ToCql()

	// build our query object
	q := gocqlx.Query(mydbpackage.Session.Query(stmt), names).BindMap(qb.M{MyTable.PrimaryKey: uuid})

	// execute the query
	if err := q.GetRelease(f); err != nil {
		return err
	}

	return nil
}

**Comment by mmatczuk** [comment]
Hi @Linuturk,
dest interface{} type must be a pointer, it should work with interface just fine GetRelease accepts interface anyway. I cannot tell more without seeing the error.
