### ISSUE TITLE
Malformated query when there are USING with a negative TLL

### ISSUE THREAD

**Issue by sagarafr** [scylladb/gocqlx#75]
When the TTL is negative (more precisely < -2), the query is malformated and accept this negative value in the query.
Pull #74

**Comment by mmatczuk** [comment]
Hi @sagarafr, thanks for contributing the test cases. I really appreciate that! How do you suggest that is fixed?

From my perspective we took a conscious decision not to return errors in QB. It's too dumb to understand query logic and even syntax sometimes, you may trick it with providing broken literals etc. As for TTL I see two alternatives:

1. make it uint - it possibly breaks existing code and forces you to do casting
1. panic

**Comment by sagarafr** [comment]
Hi @mmatczuk,
You are welcome. Make contributions are normal, to make an evolution of a big project.
I think the alternative 2 is too dangereous and can break some queries in productions without warning. Generally, on Go, panic is rarely used for the use case.
On the other hand, if the alternative 1 is well-made, I think it's can provoke a compilation error and prevent error in production.
What do you think ?

**Comment by mmatczuk** [comment]
I think it will break other users code and produce hard to understand bugs like this one:

https://play.golang.org/p/unMyVMBUFzW

**Comment by sagarafr** [comment]
Yes, I'm agree with you but we can check the overflow with this example :

[Go playground example](https://play.golang.org/p/qA07JZXh1XH)

**Comment by mmatczuk** [comment]
How would that work in practice?

**Comment by gappaa** [comment]
If we know the maximum value of an `int64` and cast a negative value of an `int64` into `uint64`, then the `uint64` must be greater than the maximum value of an `int64`

**Comment by sagarafr** [comment]
If we know the maximum value of an `int64` and cast a negative value of an `int64` into `uint64`, then the `uint64` must be greater than the maximum value of an int64 ?

**Comment by mmatczuk** [comment]
I do not think it's gonna fly. Now we allow users to specify whatever they want, if something goes wrong query will fail and then you can handle that gracefully. With this direction of changes you want to introduce a side effect that will play with aliveness of data. I'm strongly against this change as proposed. I'd suggest leaving is as is and adjusting tests.

**Comment by sagarafr** [comment]
OK. I will do that.

**Comment by sagarafr** [comment]
Pull request #74 merged
