### ISSUE TITLE
Support nested structs

### ISSUE THREAD

**Issue by rssathe** [scylladb/gocqlx#82]
What is the best way to a property defined on the root level of a cassandra table be embedded inside a nested struct as defined in go?

For example 
```
type Foo struct {
	CompanyUUID      gocql.UUID `json:"companyUUID" cql:"company_uuid"`
	Bar          *Bar   `json:"bar"`
	CreatedAt        time.Time  `cql:"created_at"`
	UpdatedAt        time.Time  `cql:"updated_at"`
}

type Bar struct {
	BazBah    bool     `json:"bazBah" cql:"baz_bah"`
}

CREATE TABLE IF NOT EXISTS {{.Keyspace}}.foo (
    company_uuid uuid,
    baz_bah boolean,
    created_at timestamp,
    updated_at timestamp,
    PRIMARY KEY (company_uuid)
);
```

A GetRelease on a Foo struct here fails with missing destination name "baz_bah" in *package.Foo

**Comment by rssathe** [comment]
Nvm fixed this by reading through reflectx and adding db:"" tag to bar!

**Comment by mmatczuk** [comment]
No need to close it, Bar needs to implement custom marshaling ex. https://github.com/scylladb/gocqlx/blob/master/iterx_test.go#L27
