### ISSUE TITLE
SELECT queries are not delivered to the replica and shard to which token belongs to

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/gocqlx#89]
HEAD: ?
scylla version: 2018.1.6

Cluster: 3 DC, 7 nodes in each DC. 
Each node has 38 shards
RF: One replica in each DC.
Client load balancing configuration: TokenAwareHostPolicy with failover to DCAwareRoundRobinPolicy

*Description* 
Customer runs a Go program that issues singular read requests however some shards are being loaded more than others a Coordinator while the load is nicely balanced on a replica side.

Below is the screenshot of a "Per Server" dashboard in a per-shard mode on one of the nodes:
![image](https://user-images.githubusercontent.com/6103981/51941454-a20f3f00-23e2-11e9-8f5d-55bb7b466278.png)

Yellow shard is *shard 1*.

We recorded CQL Tracing during the same time frame using the probabilistic tracing enabled on the same node.

Here is a raw tracing data:
[events.txt](https://github.com/scylladb/gocqlx/files/2809914/events.txt)
[sessions.txt](https://github.com/scylladb/gocqlx/files/2809915/sessions.txt)

First of all analyzing this data we see that there are 189 SELECTs out of 517 total requests.
Out of these 189 50 were handled by shard 1 as a coordinator.
And all selects handled by shard 1 were selecting a distinctive token.

Here are some filterings of the tracing data provided above:
[selects_events.txt](https://github.com/scylladb/gocqlx/files/2809942/selects_events.txt)
[selects_session_ids.txt](https://github.com/scylladb/gocqlx/files/2809943/selects_session_ids.txt)
[selects_shard1_events.txt](https://github.com/scylladb/gocqlx/files/2809944/selects_shard1_events.txt)
[selects_shard1_session_ids.txt](https://github.com/scylladb/gocqlx/files/2809945/selects_shard1_session_ids.txt)
[selects_shard1_sessions.txt](https://github.com/scylladb/gocqlx/files/2809946/selects_shard1_sessions.txt)
[selects_shard1_tokens.txt](https://github.com/scylladb/gocqlx/files/2810025/selects_shard1_tokens.txt)
[selects_shard1_targets_different_from_coordinator.txt](https://github.com/scylladb/gocqlx/files/2810039/selects_shard1_targets_different_from_coordinator.txt)

As you may see from the last filtering there are 46 selects which natural endpoints are different from the coordinator (`10.127.248.7`). 

Here are trace events of one such SELECT query:
[913b6c10-23ee-11e9-a140-000000000025.txt](https://github.com/scylladb/gocqlx/files/2810048/913b6c10-23ee-11e9-a140-000000000025.txt)

**Comment by rkuska** [comment]
I believe that this should be reported against http://github.com/scylladb/gocql

**Comment by mmatczuk** [comment]
Can you provide IP/CIDR to DC mapping.

**Comment by rkuska** [comment]
Sent on slack.

**Comment by mmatczuk** [comment]
Another strange thing is that this node made almost all the SELECT requests

```
 michal@localhost:~/downloads$ grep 10.127.251.3 sessions.txt | grep SELECT | wc -l
166
 michal@localhost:~/downloads$ grep SELECT sessions.txt | wc -l
189
```

**Comment by avikivity** [comment]
@vladzcloudius please give examples of failed queries and their traces (in a way that doesn't require combing through 10 attachments)

**Comment by rkuska** [comment]
@mmatczuk I just checked and `10.127.251.3` is using the same image as other hosts so therefore it must be using the same shard aware driver.

**Comment by mmatczuk** [comment]
@vladzcloudius @rkuska I'm closing this issue here, we can move discussion to a different project or continue in upstream. I have opened issue https://github.com/gocql/gocql/issues/1262 and submitted my fix https://github.com/gocql/gocql/pull/1261. The ScyllaDB fork is already updated.

**Comment by vladzcloudius** [comment]
@haaawk Please, verify that our Java fork doesn't suffer from the same issues. The last time I checked - it does. ;)
Also, please, check with @mmatczuk - he found a few issues in the driver itself (not related to shard-awarness). There is a good chance that Java driver has same issues too.
